/*

  BURNING TURD BAG LICENSE:
  ALL INTELLECTUAL "PROPERTY" IS THEFT!!!!
  ANY ATTEMPT TO PATENT, COPYRIGHT, OR TRADEMARK ANY PART OF THIS CODE EVER
  GRANTS THE AUTHOR THE RIGHT TO RETALIATE WITH BURNING TURD BAGS AT ANY TIME ANYWHERE
  AUTHOR DOES NOT RECOGNIZE MORAL AUTHORITY OF USPTO TO EXIST OR ENFORCE LAWS
  DO WHAT THOU WILT SHALL BE THE WHOLE OF THE LAW
  FUCK PATENTS 
  FUCK COPY"RIGHT"

 */
